# Generated by Django 4.1.5 on 2023-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_premium_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
