# Generated by Django 4.1.5 on 2023-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_premium_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
